// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Slug          string      `json:"slug"`
	Description   string      `json:"description"`
	QuestionCount int32       `json:"question_count"`
}

type Friendship struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	AddresseeID pgtype.UUID        `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID           pgtype.UUID        `json:"id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Player1ID    pgtype.UUID        `json:"player1_id"`
	Player2ID    pgtype.UUID        `json:"player2_id"`
	Player1Score int32              `json:"player1_score"`
	Player2Score int32              `json:"player2_score"`
	WinnerID     pgtype.UUID        `json:"winner_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type MatchRound struct {
	ID          pgtype.UUID `json:"id"`
	MatchID     pgtype.UUID `json:"match_id"`
	RoundNumber int32       `json:"round_number"`
	QuestionID  pgtype.UUID `json:"question_id"`
	P1Choice    pgtype.Int4 `json:"p1_choice"`
	P1Correct   pgtype.Bool `json:"p1_correct"`
	P1TimeMs    pgtype.Int4 `json:"p1_time_ms"`
	P1Points    int32       `json:"p1_points"`
	P2Choice    pgtype.Int4 `json:"p2_choice"`
	P2Correct   pgtype.Bool `json:"p2_correct"`
	P2TimeMs    pgtype.Int4 `json:"p2_time_ms"`
	P2Points    int32       `json:"p2_points"`
}

type Question struct {
	ID           pgtype.UUID        `json:"id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	QuestionText string             `json:"question_text"`
	Options      []byte             `json:"options"`
	CorrectIndex int32              `json:"correct_index"`
	Difficulty   int32              `json:"difficulty"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	FirebaseUid        string             `json:"firebase_uid"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	DefaultAvatarIndex int32              `json:"default_avatar_index"`
	Rating             int32              `json:"rating"`
	RatingWeekStart    int32              `json:"rating_week_start"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
