// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMatch = `-- name: CompleteMatch :exec
UPDATE matches
SET status = 'completed',
    player1_score = $1,
    player2_score = $2,
    winner_id = $3,
    completed_at = now()
WHERE id = $4
`

type CompleteMatchParams struct {
	P1Score  int32       `json:"p1_score"`
	P2Score  int32       `json:"p2_score"`
	WinnerID pgtype.UUID `json:"winner_id"`
	MatchID  pgtype.UUID `json:"match_id"`
}

func (q *Queries) CompleteMatch(ctx context.Context, arg CompleteMatchParams) error {
	_, err := q.db.Exec(ctx, completeMatch,
		arg.P1Score,
		arg.P2Score,
		arg.WinnerID,
		arg.MatchID,
	)
	return err
}

const countPendingFriendRequests = `-- name: CountPendingFriendRequests :one
SELECT COUNT(*) FROM friendships
WHERE addressee_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingFriendRequests(ctx context.Context, addresseeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingFriendRequests, addresseeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (requester_id, addressee_id)
VALUES ($1, $2)
RETURNING id, requester_id, addressee_id, status, created_at
`

type CreateFriendshipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (category_id, player1_id, player2_id, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, category_id, player1_id, player2_id, player1_score, player2_score, winner_id, status, created_at, completed_at
`

type CreateMatchParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Player1ID  pgtype.UUID `json:"player1_id"`
	Player2ID  pgtype.UUID `json:"player2_id"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.CategoryID, arg.Player1ID, arg.Player2ID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Player1Score,
		&i.Player2Score,
		&i.WinnerID,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, username, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, firebase_uid, username, display_name, avatar_url, default_avatar_index, rating, rating_week_start, last_seen_at, created_at
`

type CreateUserParams struct {
	FirebaseUid string      `json:"firebase_uid"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DefaultAvatarIndex,
		&i.Rating,
		&i.RatingWeekStart,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByFirebaseUID = `-- name: FindUserByFirebaseUID :one
SELECT id, firebase_uid, username, display_name, avatar_url, default_avatar_index, rating, rating_week_start, last_seen_at, created_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) FindUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DefaultAvatarIndex,
		&i.Rating,
		&i.RatingWeekStart,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, firebase_uid, username, display_name, avatar_url, default_avatar_index, rating, rating_week_start, last_seen_at, created_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DefaultAvatarIndex,
		&i.Rating,
		&i.RatingWeekStart,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, firebase_uid, username, display_name, avatar_url, default_avatar_index, rating, rating_week_start, last_seen_at, created_at FROM users WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DefaultAvatarIndex,
		&i.Rating,
		&i.RatingWeekStart,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, description, question_count FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.QuestionCount,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, requester_id, addressee_id, status, created_at FROM friendships WHERE id = $1
`

func (q *Queries) GetFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getH2HRecord = `-- name: GetH2HRecord :one
SELECT
    COUNT(*) FILTER (WHERE winner_id = $1) as wins,
    COUNT(*) FILTER (WHERE winner_id = $2) as losses
FROM matches
WHERE status = 'completed'
  AND ((player1_id = $1 AND player2_id = $2)
    OR (player1_id = $2 AND player2_id = $1))
`

type GetH2HRecordParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	OpponentID pgtype.UUID `json:"opponent_id"`
}

type GetH2HRecordRow struct {
	Wins   int64 `json:"wins"`
	Losses int64 `json:"losses"`
}

func (q *Queries) GetH2HRecord(ctx context.Context, arg GetH2HRecordParams) (GetH2HRecordRow, error) {
	row := q.db.QueryRow(ctx, getH2HRecord, arg.UserID, arg.OpponentID)
	var i GetH2HRecordRow
	err := row.Scan(&i.Wins, &i.Losses)
	return i, err
}

const getMatchWithRounds = `-- name: GetMatchWithRounds :many
SELECT mr.id, mr.match_id, mr.round_number, mr.question_id, mr.p1_choice, mr.p1_correct, mr.p1_time_ms, mr.p1_points, mr.p2_choice, mr.p2_correct, mr.p2_time_ms, mr.p2_points, q.question_text, q.options, q.correct_index
FROM match_rounds mr
JOIN questions q ON q.id = mr.question_id
WHERE mr.match_id = $1
ORDER BY mr.round_number
`

type GetMatchWithRoundsRow struct {
	ID           pgtype.UUID `json:"id"`
	MatchID      pgtype.UUID `json:"match_id"`
	RoundNumber  int32       `json:"round_number"`
	QuestionID   pgtype.UUID `json:"question_id"`
	P1Choice     pgtype.Int4 `json:"p1_choice"`
	P1Correct    pgtype.Bool `json:"p1_correct"`
	P1TimeMs     pgtype.Int4 `json:"p1_time_ms"`
	P1Points     int32       `json:"p1_points"`
	P2Choice     pgtype.Int4 `json:"p2_choice"`
	P2Correct    pgtype.Bool `json:"p2_correct"`
	P2TimeMs     pgtype.Int4 `json:"p2_time_ms"`
	P2Points     int32       `json:"p2_points"`
	QuestionText string      `json:"question_text"`
	Options      []byte      `json:"options"`
	CorrectIndex int32       `json:"correct_index"`
}

func (q *Queries) GetMatchWithRounds(ctx context.Context, matchID pgtype.UUID) ([]GetMatchWithRoundsRow, error) {
	rows, err := q.db.Query(ctx, getMatchWithRounds, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchWithRoundsRow{}
	for rows.Next() {
		var i GetMatchWithRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.RoundNumber,
			&i.QuestionID,
			&i.P1Choice,
			&i.P1Correct,
			&i.P1TimeMs,
			&i.P1Points,
			&i.P2Choice,
			&i.P2Correct,
			&i.P2TimeMs,
			&i.P2Points,
			&i.QuestionText,
			&i.Options,
			&i.CorrectIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBestCategory = `-- name: GetUserBestCategory :one
SELECT c.name,
       ROUND(100.0 * SUM(CASE WHEN
           (m.player1_id = $1 AND mr.p1_correct = true) OR
           (m.player2_id = $1 AND mr.p2_correct = true)
           THEN 1 ELSE 0 END)::numeric / NULLIF(COUNT(*), 0), 1) as accuracy_pct
FROM match_rounds mr
JOIN matches m ON m.id = mr.match_id
JOIN categories c ON c.id = m.category_id
WHERE (m.player1_id = $1 OR m.player2_id = $1)
  AND m.status = 'completed'
GROUP BY c.id, c.name
ORDER BY accuracy_pct DESC
LIMIT 1
`

type GetUserBestCategoryRow struct {
	Name        string         `json:"name"`
	AccuracyPct pgtype.Numeric `json:"accuracy_pct"`
}

func (q *Queries) GetUserBestCategory(ctx context.Context, userID pgtype.UUID) (GetUserBestCategoryRow, error) {
	row := q.db.QueryRow(ctx, getUserBestCategory, userID)
	var i GetUserBestCategoryRow
	err := row.Scan(&i.Name, &i.AccuracyPct)
	return i, err
}

const insertMatchRound = `-- name: InsertMatchRound :exec
INSERT INTO match_rounds (match_id, round_number, question_id, p1_choice, p1_correct, p1_time_ms, p1_points, p2_choice, p2_correct, p2_time_ms, p2_points)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertMatchRoundParams struct {
	MatchID     pgtype.UUID `json:"match_id"`
	RoundNumber int32       `json:"round_number"`
	QuestionID  pgtype.UUID `json:"question_id"`
	P1Choice    pgtype.Int4 `json:"p1_choice"`
	P1Correct   pgtype.Bool `json:"p1_correct"`
	P1TimeMs    pgtype.Int4 `json:"p1_time_ms"`
	P1Points    int32       `json:"p1_points"`
	P2Choice    pgtype.Int4 `json:"p2_choice"`
	P2Correct   pgtype.Bool `json:"p2_correct"`
	P2TimeMs    pgtype.Int4 `json:"p2_time_ms"`
	P2Points    int32       `json:"p2_points"`
}

func (q *Queries) InsertMatchRound(ctx context.Context, arg InsertMatchRoundParams) error {
	_, err := q.db.Exec(ctx, insertMatchRound,
		arg.MatchID,
		arg.RoundNumber,
		arg.QuestionID,
		arg.P1Choice,
		arg.P1Correct,
		arg.P1TimeMs,
		arg.P1Points,
		arg.P2Choice,
		arg.P2Correct,
		arg.P2TimeMs,
		arg.P2Points,
	)
	return err
}

const listAcceptedFriends = `-- name: ListAcceptedFriends :many
SELECT u.id, u.firebase_uid, u.username, u.display_name, u.avatar_url, u.default_avatar_index, u.rating, u.rating_week_start, u.last_seen_at, u.created_at FROM users u
JOIN friendships f ON (
    (f.requester_id = $1 AND f.addressee_id = u.id) OR
    (f.addressee_id = $1 AND f.requester_id = u.id)
)
WHERE f.status = 'accepted'
`

func (q *Queries) ListAcceptedFriends(ctx context.Context, userID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.DefaultAvatarIndex,
			&i.Rating,
			&i.RatingWeekStart,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, question_count FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFriendRequests = `-- name: ListPendingFriendRequests :many
SELECT f.id, f.requester_id, f.addressee_id, f.status, f.created_at, u.username, u.display_name, u.avatar_url, u.default_avatar_index, u.rating
FROM friendships f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
`

type ListPendingFriendRequestsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	RequesterID        pgtype.UUID        `json:"requester_id"`
	AddresseeID        pgtype.UUID        `json:"addressee_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	DefaultAvatarIndex int32              `json:"default_avatar_index"`
	Rating             int32              `json:"rating"`
}

func (q *Queries) ListPendingFriendRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListPendingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingFriendRequestsRow{}
	for rows.Next() {
		var i ListPendingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.DefaultAvatarIndex,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMatches = `-- name: ListUserMatches :many
SELECT m.id, m.category_id, m.player1_id, m.player2_id, m.player1_score, m.player2_score, m.winner_id, m.status, m.created_at, m.completed_at, c.name as category_name,
       u1.username as player1_username, u2.username as player2_username
FROM matches m
JOIN categories c ON c.id = m.category_id
JOIN users u1 ON u1.id = m.player1_id
JOIN users u2 ON u2.id = m.player2_id
WHERE (m.player1_id = $1 OR m.player2_id = $1)
  AND m.status = 'completed'
ORDER BY m.completed_at DESC
LIMIT $3 OFFSET $2
`

type ListUserMatchesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListUserMatchesRow struct {
	ID              pgtype.UUID        `json:"id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Player1ID       pgtype.UUID        `json:"player1_id"`
	Player2ID       pgtype.UUID        `json:"player2_id"`
	Player1Score    int32              `json:"player1_score"`
	Player2Score    int32              `json:"player2_score"`
	WinnerID        pgtype.UUID        `json:"winner_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CategoryName    string             `json:"category_name"`
	Player1Username string             `json:"player1_username"`
	Player2Username string             `json:"player2_username"`
}

func (q *Queries) ListUserMatches(ctx context.Context, arg ListUserMatchesParams) ([]ListUserMatchesRow, error) {
	rows, err := q.db.Query(ctx, listUserMatches, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMatchesRow{}
	for rows.Next() {
		var i ListUserMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Player1Score,
			&i.Player2Score,
			&i.WinnerID,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.CategoryName,
			&i.Player1Username,
			&i.Player2Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRandomQuestions = `-- name: LoadRandomQuestions :many
SELECT id, category_id, question_text, options, correct_index, difficulty, created_at FROM questions
WHERE category_id = $1
ORDER BY random()
LIMIT $2
`

type LoadRandomQuestionsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) LoadRandomQuestions(ctx context.Context, arg LoadRandomQuestionsParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, loadRandomQuestions, arg.CategoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.Options,
			&i.CorrectIndex,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, firebase_uid, username, display_name, avatar_url, default_avatar_index, rating, rating_week_start, last_seen_at, created_at FROM users WHERE username LIKE $1 || '%' ORDER BY username LIMIT 10
`

func (q *Queries) SearchUsersByUsername(ctx context.Context, dollar_1 pgtype.Text) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.DefaultAvatarIndex,
			&i.Rating,
			&i.RatingWeekStart,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBothRatings = `-- name: UpdateBothRatings :exec
UPDATE users SET rating = CASE
    WHEN id = $1 THEN $2
    WHEN id = $3 THEN $4
END
WHERE id IN ($1, $3)
`

type UpdateBothRatingsParams struct {
	P1ID     pgtype.UUID `json:"p1_id"`
	P1Rating int32       `json:"p1_rating"`
	P2ID     pgtype.UUID `json:"p2_id"`
	P2Rating int32       `json:"p2_rating"`
}

func (q *Queries) UpdateBothRatings(ctx context.Context, arg UpdateBothRatingsParams) error {
	_, err := q.db.Exec(ctx, updateBothRatings,
		arg.P1ID,
		arg.P1Rating,
		arg.P2ID,
		arg.P2Rating,
	)
	return err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :exec
UPDATE friendships SET status = $1 WHERE id = $2
`

type UpdateFriendshipStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendshipStatus, arg.Status, arg.ID)
	return err
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastSeen, id)
	return err
}

const updateUserRating = `-- name: UpdateUserRating :exec
UPDATE users SET rating = $1 WHERE id = $2
`

type UpdateUserRatingParams struct {
	Rating int32       `json:"rating"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) error {
	_, err := q.db.Exec(ctx, updateUserRating, arg.Rating, arg.ID)
	return err
}
